Repository RileyC9/EasyGrammar, pull requests merged in 2024-04, with the labels that each got.

#46 Grammar checker
  src/components/ImageUnite.js
Labels: bug, enhancement

#47 Add Landing page and update tooltips
  .DS_Store
  src/App.js
  src/components/About.js
  src/components/Contact.js
  src/components/DefinitionList.js
  src/components/Feedback.js
  src/components/Footer.js
  src/components/Header.js
  src/components/Help.js
  src/components/ImageUnite.js
  src/components/Landing.js
  src/components/Practice.js
  src/components/SearchInput.js
  src/components/main.js
  src/img/images.jpeg
Labels: enhancement, GUI

#48 Documentation: README.md and API 1
  README.md
  githubReadmeSteps.png
  src/components/DefinitionList.js
  src/components/SampleSentence.js
  src/components/main.js
Labels: documentation

#51 modified App.test file---created unit test cases for grammar checker feature; modified Feedback file---added data test-id for grammar-analysis-report
  src/App.test.js
  src/components/Feedback.js
Labels: testing

#56 Eval in progress
  package-lock.json
  package.json
  src/components/Feedback.js
  src/components/ImageUnite.js
Labels: enhancement

#52 Update landing page and about us
  package-lock.json
  package.json
  public/index.html
  src/components/About.js
  src/components/Contact.js
  src/components/Landing.js
  src/img/aiImage.png
  src/img/feedback.png
  src/img/homepage.png
  src/img/practice.png
  src/img/ravinesh.jpg
  src/img/riley.jpg
  src/img/xavier.jpg
  src/img/yujie.jpg
Labels: GUI

#57 Handle url redirects, Add loading spinner, Update layouts
  public/_redirects
  src/components/About.js
  src/components/Contact.js
  src/components/Feedback.js
  src/components/Header.js
  src/components/ImageUnite.js
  src/components/Landing.js
  src/components/Practice.js
Labels: bug, enhancement, GUI

#59 Image generation branch to the main branch
  .DS_Store
  .github/workflows/JestTestAutomation.yml
  .gitignore
  README.md
  githubReadmeSteps.png
  package-lock.json
  package.json
  public/_redirects
  public/index.html
  src/App.js
  src/App.test.js
  src/components/About.js
  src/components/Contact.js
  src/components/DefinitionList.js
  src/components/Feedback.js
  src/components/Footer.js
  src/components/Header.js
  src/components/Help.js
  src/components/ImageUnite.js
  src/components/Landing.js
  src/components/Practice.js
  src/components/SampleSentence.js
  src/components/SearchInput.js
  src/components/main.js
  src/img/aiImage.png
  src/img/feedback.png
  src/img/fixPic.jpeg
  src/img/homepage.png
  src/img/images.jpeg
  src/img/practice.png
  src/img/ravinesh.jpg
  src/img/riley.jpg
  src/img/xavier.jpg
  src/img/yujie.jpg
  src/index.css
  src/setupTests.js
Labels: documentation, enhancement, final version

#60 modified App.test file---created test cases for evaluation feature
  src/App.test.js
Labels: testing

#62 Testes
  src/App.test.js
  src/components/Feedback.js
  src/components/ImageUnite.js
Labels: testing

#66 Update DefinitionList.js
  src/components/DefinitionList.js
Labels: documentation

#67 modified IntegrationTest.test file---created test cases for sample se…
  src/__mocks__/axios.js
  src/__test__/IntegrationTest.test.js
Labels: testing

#68 Added unit test cases and 6 Integration test cases
  src/App.test.js
  src/__mocks__/axios.js
  src/__test__/IntegrationTest.test.js
  src/components/Feedback.js
  src/components/ImageUnite.js
  src/components/main.js
Labels: testing

#63 MS 2 AI Disclosure form, Update README
  AIDeclarationForms/P2_AI_Declaration_Ravinesh_Sami_100399749.pdf
  AIDeclarationForms/P2_AI_Declaration_TingHin_Cheung_100396747.pdf
  AIDeclarationForms/P2_AI_Declaration_Xavier_Pardanaud_100309633.pdf
  AIDeclarationForms/p2_AI_Declaration_Yujie_Peng_100407970.pdf
  README.md
  README.old.md
Labels: documentation
