Repository RileyC9/EasyGrammar, pull requests merged in 2024-03, with the labels that each got.

#23 Word search
  src/App.test.js
Labels: enhancement, testing

#24 Updated main.js, DefinitionList.js:
  src/components/DefinitionList.js
  src/components/main.js
Labels: bug, question, GUI

#26 Implement sample sentence display.
  src/components/SampleSentence.js
  src/components/main.js
Labels: enhancement

#27 Sample Sentence display
  src/components/DefinitionList.js
  src/components/Footer.js
  src/components/Header.js
  src/components/SampleSentence.js
  src/components/SearchInput.js
  src/components/main.js
Labels: bug, enhancement

#38 modified app.test.js file---added test cases for Sample Sentence feature
  src/App.test.js
Labels: testing

#40 Created .github/workflows/JestTestAutomation.yml.
  .github/workflows/JestTestAutomation.yml
Labels: testing

#41 API 1 and features implementation
  .DS_Store
  .github/workflows/JestTestAutomation.yml
  package-lock.json
  package.json
  public/index.html
  public/intro.png
  public/manifest.json
  src/App.css
  src/App.js
  src/App.test.js
  src/components/Contact.js
  src/components/DefinitionList.js
  src/components/Footer.js
  src/components/Header.js
  src/components/SampleSentence.js
  src/components/SearchInput.js
  src/components/main.js
  src/index.css
  tailwind.config.js
Labels: enhancement, testing, GUI

#43 text to image
  .gitignore
  src/components/Image/fixPic.jpeg
  src/components/ImageUnite.js
Labels: enhancement

#45 Gm in progress to grammar checker
  .gitignore
  src/components/Image/fixPic.jpeg
  src/components/ImageUnite.js
Labels: enhancement

#44 Integrate AI image into GUI, Store image in local storage and read in during practice
  package-lock.json
  package.json
  src/App.js
  src/components/DefinitionList.js
  src/components/Feedback.js
  src/components/Footer.js
  src/components/Header.js
  src/components/Image/fixPic.jpeg
  src/components/ImageUnite.js
  src/components/Practice.js
  src/components/main.js
  src/img/fixPic.jpeg
  src/index.css
Labels: enhancement, GUI
